name: Playwright Tests

on:
  pull_request:
  # push:
  #   branches: [ main, master ]

  # pull_request:
  #   branches: [ main, master ]

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Build images
        run: |
          docker-compose pull
          docker-compose build
      - name: Run tests
        # docker-compose down; docker-compose up -d mysql; sleep 20; docker-compose run --rm app bash -c "npm install; npm run build; npm run start & sleep 5; npm run test-e2e"
        run: |
          docker-compose up -d db
          sleep 20
          docker-compose run --rm app bash -c "npm ci; npm run build; npm run start & sleep 5; npm run test-e2e"

    # runs-on: ubuntu-latest
    # timeout-minutes: 5
    # services:
    #   db:
    #     image: mysql:8.0
    #     env:
    #       MYSQL_DATABASE: myDatabase
    #       MYSQL_ROOT_PASSWORD: super
    #     # options: --default-authentication-plugin=mysql_native_password
    #     ports:
    #       - 3306:3306
    #     volumes:
    #       - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    # steps:
    #   - uses: actions/checkout@v3
    #   - uses: actions/setup-node@v3
    #     with:
    #       node-version: 18
    #   - name: Install dependencies
    #     run: npm ci
    #   - name: Start app and run Postman tests
    #     run: |
    #       npm run start & sleep 5
    #       npm run test-e2e

    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   run: npx playwright test
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
